"""empty message

Revision ID: 2fc631445adf
Revises: 
Create Date: 2022-04-27 16:47:02.440816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc631445adf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_offices',
    sa.Column('id__branch_office', sa.Integer(), nullable=False),
    sa.Column('name__branch_office', sa.String(length=50), nullable=False),
    sa.Column('address__branc_office', sa.String(length=50), nullable=False),
    sa.Column('phone__branch_office', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id__branch_office')
    )
    op.create_table('products',
    sa.Column('id__product', sa.Integer(), nullable=False),
    sa.Column('name__product', sa.String(length=50), nullable=False),
    sa.Column('brand__product', sa.String(length=50), nullable=False),
    sa.Column('unit__product', sa.String(length=50), nullable=False),
    sa.Column('image__product', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id__product')
    )
    op.create_table('users',
    sa.Column('id__user', sa.Integer(), nullable=False),
    sa.Column('username__user', sa.String(length=50), nullable=False),
    sa.Column('name__user', sa.String(length=50), nullable=False),
    sa.Column('lastname__user', sa.String(length=50), nullable=False),
    sa.Column('password__user', sa.String(length=250), nullable=False),
    sa.Column('role__user', sa.Enum('User', 'Administrator', name='user_role'), nullable=False),
    sa.Column('email__user', sa.String(length=30), nullable=True),
    sa.Column('phone_number__user', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id__user')
    )
    op.create_table('lists',
    sa.Column('id__list', sa.Integer(), nullable=False),
    sa.Column('name__list', sa.String(length=50), nullable=True),
    sa.Column('fk_user__list', sa.Integer(), nullable=False),
    sa.Column('created_date__list', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fk_user__list'], ['users.id__user'], ),
    sa.PrimaryKeyConstraint('id__list')
    )
    op.create_table('product_details',
    sa.Column('id_product__details', sa.Integer(), nullable=False),
    sa.Column('fk_product__product_detail', sa.Integer(), nullable=False),
    sa.Column('fk_branch_office__product_detail', sa.Integer(), nullable=False),
    sa.Column('current_price__product_detail', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fk_branch_office__product_detail'], ['branch_offices.id__branch_office'], ),
    sa.ForeignKeyConstraint(['fk_product__product_detail'], ['products.id__product'], ),
    sa.PrimaryKeyConstraint('id_product__details')
    )
    op.create_table('super_markets',
    sa.Column('id__super_market', sa.Integer(), nullable=False),
    sa.Column('name__super_market', sa.String(length=50), nullable=False),
    sa.Column('latitude__super_market', sa.String(length=50), nullable=False),
    sa.Column('longitude__super_market', sa.String(length=50), nullable=False),
    sa.Column('phone__super_market', sa.String(length=50), nullable=True),
    sa.Column('fk_branch_office__super_market', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_branch_office__super_market'], ['branch_offices.id__branch_office'], ),
    sa.PrimaryKeyConstraint('id__super_market')
    )
    op.create_table('list_details',
    sa.Column('id__list_details', sa.Integer(), nullable=False),
    sa.Column('fk_list__details_list', sa.Integer(), nullable=False),
    sa.Column('fk_product__details_list', sa.Integer(), nullable=False),
    sa.Column('fk_super_market__list_details', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_list__details_list'], ['lists.id__list'], ),
    sa.ForeignKeyConstraint(['fk_product__details_list'], ['product_details.id_product__details'], ),
    sa.ForeignKeyConstraint(['fk_super_market__list_details'], ['super_markets.id__super_market'], ),
    sa.PrimaryKeyConstraint('id__list_details')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_details')
    op.drop_table('super_markets')
    op.drop_table('product_details')
    op.drop_table('lists')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('branch_offices')
    # ### end Alembic commands ###
