"""empty message

Revision ID: 69d5c37b669e
Revises: 06647c24c612
Create Date: 2019-10-10 12:53:00.945805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69d5c37b669e'
down_revision = '06647c24c612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image__product', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image__product')
    # ### end Alembic commands ###
